Web:
  SecretKey: "fuckyou!"
  Mod: "debug"
Mysql:
  Username: "root"
  Password: "336699"
  Host: "127.0.0.1"
  Port: 3306
  Database: "mvpblog"
Redis:
  Host: "127.0.0.1:6379"
  Password: ""
  DB: 1